CREATE TABLE IF NOT EXISTS som_sales_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    store_code VARCHAR(128) NOT NULL,
    store_name VARCHAR(256),
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_som_store_tenant ON som_sales_store(tenant_id);
CREATE UNIQUE INDEX idx_som_store_code ON som_sales_store(tenant_id, platform, store_code);

CREATE TABLE IF NOT EXISTS som_sales_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    marketplace_id VARCHAR(64),
    units_sold INT NOT NULL DEFAULT 0,
    revenue DECIMAL(18, 2),
    average_price DECIMAL(18, 2),
    period_start TIMESTAMP,
    period_end TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_som_tracking_store ON som_sales_tracking(tenant_id, store_id);
CREATE INDEX idx_som_tracking_sku ON som_sales_tracking(tenant_id, seller_sku);

CREATE TABLE IF NOT EXISTS som_store_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metrics_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL,
    marketplace_id VARCHAR(64),
    total_revenue DECIMAL(18, 2),
    total_orders DECIMAL(18, 2),
    average_order_value DECIMAL(18, 2),
    return_rate DECIMAL(8, 6),
    feedback_score DECIMAL(5, 2),
    period_start TIMESTAMP,
    period_end TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_som_metrics_store ON som_store_metrics(tenant_id, store_id);
