CREATE TABLE IF NOT EXISTS fba_shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fba_shipment_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    amazon_shipment_id VARCHAR(128),
    destination_fc VARCHAR(64),
    planned_quantity INT NOT NULL DEFAULT 0,
    received_quantity INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fba_shipment_tenant ON fba_shipment(tenant_id);
CREATE UNIQUE INDEX idx_fba_shipment_amz ON fba_shipment(tenant_id, amazon_shipment_id);

CREATE TABLE IF NOT EXISTS fba_carton_label (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    fba_shipment_id VARCHAR(64) NOT NULL,
    carton_id VARCHAR(64),
    seller_sku VARCHAR(128) NOT NULL,
    quantity_per_carton INT NOT NULL DEFAULT 0,
    number_of_cartons INT NOT NULL DEFAULT 0,
    label_url VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fba_label_shipment ON fba_carton_label(tenant_id, fba_shipment_id);

CREATE TABLE IF NOT EXISTS fba_replenishment_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    destination_fc VARCHAR(64),
    suggested_quantity INT NOT NULL DEFAULT 0,
    source_warehouse_id VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fba_plan_tenant ON fba_replenishment_plan(tenant_id);
