CREATE TABLE IF NOT EXISTS tms_carrier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tms_carrier_tenant ON tms_carrier(tenant_id);

CREATE TABLE IF NOT EXISTS tms_shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64),
    carrier_id VARCHAR(64),
    tracking_no VARCHAR(128),
    destination_country VARCHAR(8),
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tms_shipment_tenant ON tms_shipment(tenant_id);
CREATE UNIQUE INDEX idx_tms_shipment_tracking ON tms_shipment(tenant_id, tracking_no);

CREATE TABLE IF NOT EXISTS tms_tracking_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    shipment_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    status VARCHAR(64),
    location VARCHAR(256),
    description TEXT,
    occurred_at TIMESTAMP,
    UNIQUE(tenant_id, shipment_id, event_id)
);

CREATE INDEX idx_tms_event_shipment ON tms_tracking_event(shipment_id);
CREATE INDEX idx_tms_event_tenant_shipment ON tms_tracking_event(tenant_id, shipment_id, occurred_at);

CREATE TABLE IF NOT EXISTS tms_shipping_cost (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    shipment_id VARCHAR(64),
    carrier_id VARCHAR(64),
    freight_cost DECIMAL(18, 2),
    fuel_surcharge DECIMAL(18, 2),
    other_fees DECIMAL(18, 2),
    total_cost DECIMAL(18, 2),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tms_cost_tenant ON tms_shipping_cost(tenant_id);
CREATE INDEX idx_tms_cost_carrier ON tms_shipping_cost(tenant_id, carrier_id);
