CREATE TABLE IF NOT EXISTS crm_customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    name VARCHAR(256),
    email VARCHAR(256),
    phone VARCHAR(64),
    country_code VARCHAR(8),
    platform VARCHAR(64),
    store_id VARCHAR(64),
    total_orders INT NOT NULL DEFAULT 0,
    total_spent DECIMAL(18, 2) NOT NULL DEFAULT 0,
    last_order_at TIMESTAMP,
    tags TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_customer_tenant ON crm_customer(tenant_id);

CREATE TABLE IF NOT EXISTS crm_service_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    customer_id VARCHAR(64),
    subject VARCHAR(512),
    description TEXT,
    assignee VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    resolution TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_ticket_tenant ON crm_service_ticket(tenant_id);

CREATE TABLE IF NOT EXISTS crm_return_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64),
    seller_sku VARCHAR(128),
    customer_id VARCHAR(64),
    quantity INT NOT NULL DEFAULT 0,
    refund_amount DECIMAL(18, 2),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    reason VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_return_tenant ON crm_return_refund(tenant_id);

CREATE TABLE IF NOT EXISTS crm_review_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    marketplace_id VARCHAR(64),
    average_rating DECIMAL(3, 2),
    total_reviews INT NOT NULL DEFAULT 0,
    positive_count INT NOT NULL DEFAULT 0,
    neutral_count INT NOT NULL DEFAULT 0,
    negative_count INT NOT NULL DEFAULT 0,
    sentiment_summary TEXT,
    analyzed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_review_tenant ON crm_review_analysis(tenant_id);
CREATE INDEX idx_crm_review_sku ON crm_review_analysis(tenant_id, seller_sku);
