CREATE TABLE IF NOT EXISTS fms_receivable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32),
    source_id VARCHAR(64),
    customer_name VARCHAR(256),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    amount DECIMAL(18, 2),
    paid_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fms_recv_tenant ON fms_receivable(tenant_id);
CREATE UNIQUE INDEX idx_fms_recv_source ON fms_receivable(tenant_id, source_type, source_id);

CREATE TABLE IF NOT EXISTS fms_payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    receivable_id VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 2),
    payment_method VARCHAR(32),
    paid_at TIMESTAMP
);

CREATE INDEX idx_fms_pay_recv ON fms_payment_record(tenant_id, receivable_id);

CREATE TABLE IF NOT EXISTS fms_cost_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_event_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    cost_type VARCHAR(32),
    source_type VARCHAR(32),
    source_id VARCHAR(64),
    seller_sku VARCHAR(128),
    marketplace_id VARCHAR(64),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    amount DECIMAL(18, 2),
    occurred_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fms_cost_tenant ON fms_cost_event(tenant_id);
CREATE INDEX idx_fms_cost_sku ON fms_cost_event(tenant_id, seller_sku);
CREATE INDEX idx_fms_cost_source ON fms_cost_event(tenant_id, source_type, source_id);

CREATE TABLE IF NOT EXISTS fms_profit_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128),
    marketplace_id VARCHAR(64),
    order_id VARCHAR(64),
    revenue DECIMAL(18, 2),
    product_cost DECIMAL(18, 2),
    shipping_cost DECIMAL(18, 2),
    fba_fee DECIMAL(18, 2),
    commission DECIMAL(18, 2),
    advertising_cost DECIMAL(18, 2),
    other_cost DECIMAL(18, 2),
    total_cost DECIMAL(18, 2),
    gross_profit DECIMAL(18, 2),
    gross_margin DECIMAL(8, 4),
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fms_profit_tenant ON fms_profit_statement(tenant_id);
CREATE INDEX idx_fms_profit_sku ON fms_profit_statement(tenant_id, seller_sku);
