-- 广告活动主表：记录租户在各广告平台的活动基础信息与自动优化开关。
CREATE TABLE IF NOT EXISTS ads_campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    platform VARCHAR(32),
    campaign_name VARCHAR(256),
    daily_budget DECIMAL(18, 2),
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    pms_optimization_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    pms_optimization_scope VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ads_campaign_tenant ON ads_campaign(tenant_id);

CREATE TABLE IF NOT EXISTS ads_keyword_bid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    keyword VARCHAR(256),
    bid_amount DECIMAL(18, 2),
    max_bid DECIMAL(18, 2),
    strategy VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ads_bid_tenant ON ads_keyword_bid(tenant_id);
CREATE INDEX idx_ads_bid_campaign ON ads_keyword_bid(tenant_id, campaign_id);

CREATE TABLE IF NOT EXISTS ads_campaign_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    spend DECIMAL(18, 2),
    impressions INT NOT NULL DEFAULT 0,
    clicks INT NOT NULL DEFAULT 0,
    ctr DECIMAL(8, 4),
    orders INT NOT NULL DEFAULT 0,
    acos DECIMAL(8, 4),
    roas DECIMAL(8, 4),
    period_start TIMESTAMP,
    period_end TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ads_perf_tenant ON ads_campaign_performance(tenant_id);
CREATE INDEX idx_ads_perf_campaign ON ads_campaign_performance(tenant_id, campaign_id);
