CREATE TABLE IF NOT EXISTS bi_report_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    report_code VARCHAR(64),
    report_name VARCHAR(256),
    report_type VARCHAR(64),
    data_source VARCHAR(64),
    query_text TEXT,
    permission_code VARCHAR(128),
    data_level VARCHAR(64),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_bi_report_tenant ON bi_report_definition(tenant_id);
CREATE UNIQUE INDEX idx_bi_report_code ON bi_report_definition(tenant_id, report_code);

CREATE TABLE IF NOT EXISTS bi_kpi_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    kpi_code VARCHAR(64),
    kpi_name VARCHAR(256),
    category VARCHAR(64),
    value DECIMAL(18, 4),
    target_value DECIMAL(18, 4),
    unit VARCHAR(16),
    status VARCHAR(32) NOT NULL DEFAULT 'ON_TRACK',
    measured_at TIMESTAMP
);

CREATE INDEX idx_bi_kpi_tenant ON bi_kpi_metric(tenant_id);
CREATE INDEX idx_bi_kpi_code ON bi_kpi_metric(tenant_id, kpi_code);
CREATE INDEX idx_bi_kpi_category ON bi_kpi_metric(tenant_id, category);

CREATE TABLE IF NOT EXISTS bi_dashboard_widget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    widget_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    widget_code VARCHAR(64),
    widget_name VARCHAR(256),
    widget_type VARCHAR(32),
    config TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_bi_widget_tenant ON bi_dashboard_widget(tenant_id);
