ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS plan_id VARCHAR(64);
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS carrier VARCHAR(64);
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(128);
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS carton_count INT NOT NULL DEFAULT 0;
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS total_weight DECIMAL(18, 3) NOT NULL DEFAULT 0;
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS packed_at TIMESTAMP;
ALTER TABLE fba_shipment ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_fba_shipment_plan ON fba_shipment(tenant_id, plan_id);
CREATE INDEX IF NOT EXISTS idx_fba_shipment_tracking ON fba_shipment(tenant_id, tracking_no);

CREATE TABLE IF NOT EXISTS fba_inbound_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    warehouse_id VARCHAR(64) NOT NULL,
    plan_name VARCHAR(128) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    planned_quantity INT NOT NULL DEFAULT 0,
    store_id VARCHAR(64),
    site_code VARCHAR(64),
    source_plan_id VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fba_inbound_plan_tenant ON fba_inbound_plan(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fba_inbound_plan_warehouse ON fba_inbound_plan(tenant_id, warehouse_id);

CREATE TABLE IF NOT EXISTS fba_shipment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    shipment_id VARCHAR(64) NOT NULL,
    product_id VARCHAR(64),
    seller_sku VARCHAR(128) NOT NULL,
    fnsku VARCHAR(128),
    quantity INT NOT NULL DEFAULT 0,
    box_quantity INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fba_shipment_item_tenant ON fba_shipment_item(tenant_id, shipment_id);

CREATE TABLE IF NOT EXISTS fba_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    country_code VARCHAR(32) NOT NULL,
    address VARCHAR(256) NOT NULL,
    location_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fba_location_tenant ON fba_location(tenant_id);

CREATE TABLE IF NOT EXISTS fba_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    warehouse_id VARCHAR(64) NOT NULL,
    product_id VARCHAR(64),
    seller_sku VARCHAR(128) NOT NULL,
    fnsku VARCHAR(128),
    quantity INT NOT NULL DEFAULT 0,
    store_id VARCHAR(64),
    site_code VARCHAR(64),
    inventory_age_days INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fba_inventory_tenant ON fba_inventory(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fba_inventory_query ON fba_inventory(tenant_id, seller_sku, store_id, site_code, warehouse_id);
