CREATE TABLE IF NOT EXISTS bi_metric_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    metric_name VARCHAR(256) NOT NULL,
    category VARCHAR(64) NOT NULL,
    formula TEXT,
    unit VARCHAR(32),
    permission_code VARCHAR(128),
    data_level VARCHAR(64),
    description TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_bi_metric_tenant ON bi_metric_definition(tenant_id);
CREATE UNIQUE INDEX idx_bi_metric_code ON bi_metric_definition(tenant_id, metric_code);
CREATE INDEX idx_bi_metric_category ON bi_metric_definition(tenant_id, category);
