-- 广告活动的 PMS 优化字段已并入建表脚本，保留此文件仅继续承载策略与动作日志表。

CREATE TABLE IF NOT EXISTS ads_strategy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    strategy_code VARCHAR(64) NOT NULL,
    strategy_name VARCHAR(256) NOT NULL,
    strategy_type VARCHAR(64) NOT NULL,
    target_campaign_id VARCHAR(64) NOT NULL,
    conditions_json TEXT,
    actions_json TEXT,
    pms_generated BOOLEAN NOT NULL DEFAULT FALSE,
    schedule_expression VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    last_executed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ads_strategy_tenant ON ads_strategy(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ads_strategy_campaign ON ads_strategy(tenant_id, target_campaign_id);

CREATE TABLE IF NOT EXISTS ads_pms_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64),
    bid_id VARCHAR(64),
    action_type VARCHAR(64) NOT NULL,
    before_value TEXT,
    after_value TEXT,
    pms_reason VARCHAR(512),
    can_rollback BOOLEAN NOT NULL DEFAULT TRUE,
    rolled_back BOOLEAN NOT NULL DEFAULT FALSE,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rolled_back_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ads_action_log_tenant ON ads_pms_action_log(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ads_action_log_campaign ON ads_pms_action_log(tenant_id, campaign_id);
