ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(512);
ALTER TABLE oms_order_line ADD COLUMN IF NOT EXISTS estimated_unit_cost DECIMAL(18, 4);

CREATE TABLE IF NOT EXISTS oms_order_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    refund_amount DECIMAL(18, 4) NOT NULL,
    refund_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_oms_order_refund_tenant ON oms_order_refund(tenant_id, order_id);

CREATE TABLE IF NOT EXISTS oms_order_risk_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    risk_type VARCHAR(64) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    suggested_action VARCHAR(128),
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_oms_order_risk_check_tenant ON oms_order_risk_check(tenant_id, order_id);

CREATE TABLE IF NOT EXISTS oms_buyer_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    buyer_name VARCHAR(128) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, buyer_name)
);

CREATE INDEX IF NOT EXISTS idx_oms_buyer_blacklist_tenant ON oms_buyer_blacklist(tenant_id);
