CREATE TABLE IF NOT EXISTS wms_inventory_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    warehouse_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    quantity INT NOT NULL,
    before_on_hand INT NOT NULL,
    before_reserved INT NOT NULL,
    after_on_hand INT NOT NULL,
    after_reserved INT NOT NULL,
    reference_type VARCHAR(64),
    reference_id VARCHAR(64),
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wms_inventory_txn_tenant_wh ON wms_inventory_transaction(tenant_id, warehouse_id, created_at DESC);
CREATE INDEX idx_wms_inventory_txn_tenant_sku ON wms_inventory_transaction(tenant_id, seller_sku, created_at DESC);
