CREATE TABLE IF NOT EXISTS oms_fulfillment_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    split_shipment BOOLEAN NOT NULL DEFAULT FALSE,
    partial_shipment BOOLEAN NOT NULL DEFAULT FALSE,
    estimated_shipping_cost DECIMAL(18, 4),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, order_id)
);

CREATE TABLE IF NOT EXISTS oms_fulfillment_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id VARCHAR(64) NOT NULL UNIQUE,
    plan_id VARCHAR(64) NOT NULL,
    warehouse_id VARCHAR(64),
    warehouse_code VARCHAR(64),
    carrier_code VARCHAR(64),
    carrier_name VARCHAR(128),
    destination_country VARCHAR(16) NOT NULL,
    service_level VARCHAR(32),
    status VARCHAR(32) NOT NULL,
    total_quantity INT NOT NULL DEFAULT 0,
    total_amount DECIMAL(18, 4) NOT NULL DEFAULT 0,
    estimated_shipping_cost DECIMAL(18, 4),
    estimated_delivery_days INT,
    note VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS oms_fulfillment_package_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_line_id VARCHAR(64) NOT NULL UNIQUE,
    package_id VARCHAR(64) NOT NULL,
    order_line_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(18, 4) NOT NULL,
    line_amount DECIMAL(18, 4) NOT NULL
);

CREATE INDEX idx_oms_fulfillment_plan_tenant_order ON oms_fulfillment_plan(tenant_id, order_id);
CREATE INDEX idx_oms_fulfillment_package_plan ON oms_fulfillment_package(plan_id);
CREATE INDEX idx_oms_fulfillment_package_line_package ON oms_fulfillment_package_line(package_id);
