ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS carrier_id VARCHAR(64);
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS shipment_id VARCHAR(64);
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(128);
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP;
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS platform_sync_status VARCHAR(32) NOT NULL DEFAULT 'NOT_SYNCED';
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS platform_sync_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS platform_sync_error VARCHAR(255);
ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS platform_synced_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_oms_fulfillment_package_tracking
    ON oms_fulfillment_package(plan_id, tracking_no);

CREATE TABLE IF NOT EXISTS oms_platform_shipment_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    package_id VARCHAR(64) NOT NULL,
    platform VARCHAR(64) NOT NULL,
    platform_order_no VARCHAR(128) NOT NULL,
    tracking_no VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    attempt_no INT NOT NULL DEFAULT 1,
    error_message VARCHAR(255),
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_oms_platform_ship_sync_order
    ON oms_platform_shipment_sync_log(tenant_id, order_id, synced_at DESC);
