CREATE TABLE IF NOT EXISTS fms_platform_bill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    store VARCHAR(64) NOT NULL,
    bill_type VARCHAR(32) NOT NULL,
    period VARCHAR(7) NOT NULL,
    seller_sku VARCHAR(128),
    marketplace_id VARCHAR(64),
    source_type VARCHAR(64),
    source_id VARCHAR(64),
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    amount DECIMAL(18, 2) NOT NULL,
    raw_data CLOB,
    status VARCHAR(32) NOT NULL DEFAULT 'IMPORTED',
    settlement_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_platform_bill_tenant
    ON fms_platform_bill(tenant_id);

CREATE INDEX IF NOT EXISTS idx_fms_platform_bill_platform_store
    ON fms_platform_bill(tenant_id, platform, store);

CREATE INDEX IF NOT EXISTS idx_fms_platform_bill_source
    ON fms_platform_bill(tenant_id, source_type, source_id);
