CREATE TABLE IF NOT EXISTS fms_payment_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    po_id VARCHAR(64),
    supplier_id VARCHAR(64),
    amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    request_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    requested_by VARCHAR(64) NOT NULL,
    approval_flow CLOB,
    paid_by VARCHAR(64),
    paid_at TIMESTAMP,
    writeoff_status VARCHAR(32) NOT NULL DEFAULT 'UNWRITTEN',
    writeoff_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_payment_request_tenant
    ON fms_payment_request(tenant_id);

CREATE INDEX IF NOT EXISTS idx_fms_payment_request_supplier
    ON fms_payment_request(tenant_id, supplier_id);

CREATE TABLE IF NOT EXISTS fms_write_off (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writeoff_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    ref_type VARCHAR(32) NOT NULL,
    ref_id VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    approved_by VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_write_off_tenant
    ON fms_write_off(tenant_id);

CREATE INDEX IF NOT EXISTS idx_fms_write_off_ref
    ON fms_write_off(tenant_id, ref_type, ref_id);

CREATE TABLE IF NOT EXISTS fms_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recon_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    party_id VARCHAR(64) NOT NULL,
    party_name VARCHAR(128),
    period VARCHAR(7) NOT NULL,
    payable_amount DECIMAL(18, 2) NOT NULL,
    paid_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    items CLOB,
    difference_items CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_reconciliation_tenant
    ON fms_reconciliation(tenant_id);

CREATE INDEX IF NOT EXISTS idx_fms_reconciliation_type_party
    ON fms_reconciliation(tenant_id, type, party_id);
