CREATE TABLE IF NOT EXISTS fms_payment_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    approver_id VARCHAR(64) NOT NULL,
    approval_level INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    comment CLOB,
    approved_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_payment_approval_request
    ON fms_payment_approval(tenant_id, request_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fms_payment_approval_level
    ON fms_payment_approval(tenant_id, request_id, approval_level);
