CREATE TABLE IF NOT EXISTS fms_platform_settlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    store VARCHAR(64) NOT NULL,
    settlement_type VARCHAR(32) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    reconciled_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    linked_bill_count INT NOT NULL DEFAULT 0,
    received_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    settlement_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    withdrawal_status VARCHAR(32) NOT NULL DEFAULT 'UNREQUESTED',
    withdrawal_reference VARCHAR(64),
    forex_status VARCHAR(32) NOT NULL DEFAULT 'UNSETTLED',
    forex_rate DECIMAL(18, 6),
    received_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fms_platform_settlement_tenant
    ON fms_platform_settlement(tenant_id);

CREATE INDEX IF NOT EXISTS idx_fms_platform_settlement_platform_store
    ON fms_platform_settlement(tenant_id, platform, store);

CREATE INDEX IF NOT EXISTS idx_fms_platform_settlement_status
    ON fms_platform_settlement(tenant_id, status, withdrawal_status, forex_status);
