ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS company_name VARCHAR(256);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS credit_rating VARCHAR(32);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS lead_time_days INT DEFAULT 0;
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS moq INT DEFAULT 0;
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'ACTIVE';
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
UPDATE scm_supplier SET status = 'ACTIVE' WHERE status IS NULL;
UPDATE scm_supplier SET updated_at = created_at WHERE updated_at IS NULL;

ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS po_number VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS payment_terms VARCHAR(128);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS shipping_terms VARCHAR(128);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS purchase_type VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS expected_delivery_date TIMESTAMP;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS actual_delivery_date TIMESTAMP;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS created_by VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS approved_by VARCHAR(64);

ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS product_id VARCHAR(64);
ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS total_price DECIMAL(18, 4);
ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS expected_date TIMESTAMP;

CREATE TABLE IF NOT EXISTS scm_supplier_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    supplier_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    role VARCHAR(128),
    email VARCHAR(128),
    phone VARCHAR(64),
    primary_contact BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scm_supplier_contact_supplier
    ON scm_supplier_contact(tenant_id, supplier_id);

CREATE TABLE IF NOT EXISTS scm_supplier_qualification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qualification_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    supplier_id VARCHAR(64) NOT NULL,
    qualification_type VARCHAR(64) NOT NULL,
    qualification_no VARCHAR(128) NOT NULL,
    issued_by VARCHAR(128),
    valid_from TIMESTAMP,
    valid_until TIMESTAMP,
    status VARCHAR(32),
    remark VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scm_supplier_qualification_supplier
    ON scm_supplier_qualification(tenant_id, supplier_id);

CREATE TABLE IF NOT EXISTS scm_supplier_score (
    score_id VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    supplier_id VARCHAR(64) NOT NULL,
    quality_score DECIMAL(5, 2),
    delivery_score DECIMAL(5, 2),
    price_score DECIMAL(5, 2),
    service_score DECIMAL(5, 2),
    overall_score DECIMAL(5, 2),
    evaluation_count INT NOT NULL DEFAULT 0,
    scored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (score_id)
);

ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS quality_score DECIMAL(5, 2);
ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS delivery_score DECIMAL(5, 2);
ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS price_score DECIMAL(5, 2);
ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS service_score DECIMAL(5, 2);
ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS overall_score DECIMAL(5, 2);
ALTER TABLE scm_supplier_score ADD COLUMN IF NOT EXISTS evaluation_count INT DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_scm_supplier_score_tenant_supplier
    ON scm_supplier_score(tenant_id, supplier_id);
