CREATE TABLE IF NOT EXISTS scm_purchase_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    plan_number VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'GENERATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scm_plan_tenant
    ON scm_purchase_plan(tenant_id);

CREATE TABLE IF NOT EXISTS scm_purchase_plan_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(64) NOT NULL,
    plan_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    order_demand_quantity INT NOT NULL DEFAULT 0,
    replenishment_demand_quantity INT NOT NULL DEFAULT 0,
    available_inventory_quantity INT NOT NULL DEFAULT 0,
    in_purchasing_quantity INT NOT NULL DEFAULT 0,
    suggested_purchase_quantity INT NOT NULL DEFAULT 0,
    order_source_refs TEXT,
    suggestion_source_refs TEXT,
    line_status VARCHAR(32) NOT NULL DEFAULT 'GENERATED',
    linked_po_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plan_id, line_id)
);

CREATE INDEX IF NOT EXISTS idx_scm_plan_line_plan
    ON scm_purchase_plan_line(plan_id);

CREATE INDEX IF NOT EXISTS idx_scm_plan_line_sku
    ON scm_purchase_plan_line(plan_id, seller_sku);
