CREATE TABLE IF NOT EXISTS iam_data_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_ids JSONB NOT NULL DEFAULT '[]',
    scope_type VARCHAR(32) NOT NULL DEFAULT 'INCLUDE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_iam_data_scope_user ON iam_data_scope(tenant_id, user_id);
CREATE INDEX idx_iam_data_scope_type ON iam_data_scope(resource_type);
