CREATE TABLE IF NOT EXISTS fba_carton_label (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    fba_shipment_id VARCHAR(64) NOT NULL,
    carton_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    quantity_per_carton INT NOT NULL,
    number_of_cartons INT NOT NULL,
    label_url VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fba_carton_label_shipment ON fba_carton_label(tenant_id, fba_shipment_id);

CREATE TABLE IF NOT EXISTS fba_replenishment_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    destination_fc VARCHAR(64) NOT NULL,
    suggested_quantity INT NOT NULL,
    source_warehouse_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fba_replenishment_plan_tenant ON fba_replenishment_plan(tenant_id);

CREATE TABLE IF NOT EXISTS tms_shipping_cost (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    shipment_id VARCHAR(64) NOT NULL,
    carrier_id VARCHAR(64) NOT NULL,
    freight_cost DECIMAL(18, 4) NOT NULL,
    fuel_surcharge DECIMAL(18, 4) NOT NULL DEFAULT 0,
    other_fees DECIMAL(18, 4) NOT NULL DEFAULT 0,
    total_cost DECIMAL(18, 4) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tms_shipping_cost_tenant ON tms_shipping_cost(tenant_id);
CREATE INDEX idx_tms_shipping_cost_carrier ON tms_shipping_cost(tenant_id, carrier_id);

CREATE TABLE IF NOT EXISTS crm_return_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    quantity INT NOT NULL,
    refund_amount DECIMAL(18, 4) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_return_refund_tenant ON crm_return_refund(tenant_id);
CREATE INDEX idx_crm_return_refund_order ON crm_return_refund(tenant_id, order_id);

CREATE TABLE IF NOT EXISTS crm_review_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    marketplace_id VARCHAR(64),
    average_rating DECIMAL(3, 2) NOT NULL,
    total_reviews INT NOT NULL,
    positive_count INT NOT NULL,
    neutral_count INT NOT NULL,
    negative_count INT NOT NULL,
    sentiment_summary VARCHAR(1024),
    analyzed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_crm_review_analysis_tenant ON crm_review_analysis(tenant_id);
CREATE INDEX idx_crm_review_analysis_sku ON crm_review_analysis(tenant_id, seller_sku);

CREATE TABLE IF NOT EXISTS bi_kpi_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    kpi_code VARCHAR(128) NOT NULL,
    kpi_name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL,
    value DECIMAL(18, 4) NOT NULL,
    target_value DECIMAL(18, 4),
    unit VARCHAR(32),
    measured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_bi_kpi_metric_tenant ON bi_kpi_metric(tenant_id);
CREATE INDEX idx_bi_kpi_metric_category ON bi_kpi_metric(tenant_id, category);

CREATE TABLE IF NOT EXISTS bi_dashboard_widget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    widget_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    widget_code VARCHAR(128) NOT NULL,
    widget_name VARCHAR(128) NOT NULL,
    widget_type VARCHAR(64) NOT NULL,
    config JSONB NOT NULL DEFAULT '{}',
    sort_order INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, widget_code)
);

CREATE TABLE IF NOT EXISTS ads_keyword_bid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    keyword VARCHAR(128) NOT NULL,
    bid_amount DECIMAL(18, 4) NOT NULL,
    max_bid DECIMAL(18, 4),
    strategy VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ads_keyword_bid_campaign ON ads_keyword_bid(tenant_id, campaign_id);

CREATE TABLE IF NOT EXISTS ads_campaign_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    spend DECIMAL(18, 4) NOT NULL,
    impressions INT NOT NULL,
    clicks INT NOT NULL,
    ctr DECIMAL(8, 4) NOT NULL,
    orders INT NOT NULL,
    acos DECIMAL(8, 4) NOT NULL,
    roas DECIMAL(8, 4) NOT NULL,
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ads_campaign_performance_campaign ON ads_campaign_performance(tenant_id, campaign_id);

CREATE TABLE IF NOT EXISTS pdm_selection_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    category_id VARCHAR(64),
    source VARCHAR(64) NOT NULL,
    source_reference VARCHAR(512),
    market_analysis CLOB,
    profit_estimation CLOB,
    status VARCHAR(32) NOT NULL,
    reviewer VARCHAR(128),
    review_comment VARCHAR(1024),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_selection_proposal_tenant ON pdm_selection_proposal(tenant_id);

CREATE TABLE IF NOT EXISTS som_sales_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    store_id VARCHAR(64) NOT NULL,
    activity_name VARCHAR(255) NOT NULL,
    activity_type VARCHAR(64) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_som_sales_activity_tenant ON som_sales_activity(tenant_id);

CREATE TABLE IF NOT EXISTS wms_inventory_prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    warehouse_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    current_stock INT NOT NULL,
    avg_daily_sales DECIMAL(18, 4) NOT NULL,
    predicted_7d INT NOT NULL,
    predicted_30d INT NOT NULL,
    days_of_stock INT NOT NULL,
    prediction_level VARCHAR(32) NOT NULL,
    suggested_reorder_qty INT NOT NULL,
    predicted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wms_inventory_prediction_tenant ON wms_inventory_prediction(tenant_id, warehouse_id);

CREATE TABLE IF NOT EXISTS scm_replenishment_suggestion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    warehouse_id VARCHAR(64) NOT NULL,
    current_stock INT NOT NULL,
    suggested_qty INT NOT NULL,
    avg_daily_sales DECIMAL(18, 4) NOT NULL,
    lead_time_days INT NOT NULL,
    safety_stock INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scm_replenishment_suggestion_tenant ON scm_replenishment_suggestion(tenant_id);

CREATE TABLE IF NOT EXISTS fms_cost_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_event_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    cost_type VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    amount DECIMAL(18, 4) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    source_type VARCHAR(64),
    source_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fms_cost_event_tenant ON fms_cost_event(tenant_id);
CREATE INDEX idx_fms_cost_event_sku ON fms_cost_event(tenant_id, seller_sku);

CREATE TABLE IF NOT EXISTS fms_profit_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    revenue DECIMAL(18, 4) NOT NULL,
    cogs DECIMAL(18, 4) NOT NULL,
    shipping_cost DECIMAL(18, 4) NOT NULL,
    ad_cost DECIMAL(18, 4) NOT NULL,
    other_cost DECIMAL(18, 4) NOT NULL,
    net_profit DECIMAL(18, 4) NOT NULL,
    margin DECIMAL(8, 4) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, seller_sku, period_start, period_end)
);

CREATE INDEX idx_fms_profit_summary_tenant ON fms_profit_summary(tenant_id);
