CREATE TABLE IF NOT EXISTS sys_pms_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    erp_reference_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    recommendation_id VARCHAR(64) NOT NULL,
    domain VARCHAR(64) NOT NULL,
    recommendation_type VARCHAR(64) NOT NULL,
    object_type VARCHAR(64),
    target_object_type VARCHAR(64),
    target_object_id VARCHAR(64),
    content TEXT NOT NULL,
    score DECIMAL(8, 4),
    confidence DECIMAL(8, 4),
    evidence_chain_id VARCHAR(64),
    data_sources VARCHAR(1024),
    risk_flags VARCHAR(1024),
    explainability TEXT,
    requested_action VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    approval_policy VARCHAR(64),
    rejection_reason VARCHAR(512),
    execution_result TEXT,
    measured_result TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pms_rec_tenant ON sys_pms_recommendation(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pms_rec_domain ON sys_pms_recommendation(tenant_id, domain);
CREATE INDEX IF NOT EXISTS idx_pms_rec_status ON sys_pms_recommendation(tenant_id, status);

CREATE TABLE IF NOT EXISTS fms_cost_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_event_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    domain VARCHAR(64) NOT NULL,
    cost_type VARCHAR(64) NOT NULL,
    reference_id VARCHAR(64),
    amount DECIMAL(18, 4) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE fms_cost_event ADD COLUMN IF NOT EXISTS domain VARCHAR(64);
ALTER TABLE fms_cost_event ADD COLUMN IF NOT EXISTS reference_id VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_cost_event_tenant ON fms_cost_event(tenant_id);
CREATE INDEX IF NOT EXISTS idx_cost_event_domain ON fms_cost_event(tenant_id, domain);

CREATE TABLE IF NOT EXISTS iam_auth_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL,
    permissions VARCHAR(2048),
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auth_token_tenant ON iam_auth_token(tenant_id);
CREATE INDEX IF NOT EXISTS idx_auth_token_user ON iam_auth_token(tenant_id, user_id);

ALTER TABLE iam_user_account ADD COLUMN IF NOT EXISTS roles VARCHAR(1024);
ALTER TABLE tms_shipment ADD COLUMN IF NOT EXISTS carrier_code VARCHAR(64);
ALTER TABLE tms_shipment ADD COLUMN IF NOT EXISTS origin_warehouse_id VARCHAR(64);
ALTER TABLE tms_shipment ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(18, 4);
ALTER TABLE tms_shipment ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP;
ALTER TABLE tms_shipment ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP;

ALTER TABLE crm_service_ticket ADD COLUMN IF NOT EXISTS type VARCHAR(64);
ALTER TABLE crm_service_ticket ADD COLUMN IF NOT EXISTS priority VARCHAR(32);
ALTER TABLE crm_service_ticket ADD COLUMN IF NOT EXISTS assignee_id VARCHAR(64);
ALTER TABLE crm_service_ticket ADD COLUMN IF NOT EXISTS order_id VARCHAR(64);

ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS seller_sku VARCHAR(128);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS quantity INT;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS unit_price DECIMAL(18, 4);
