CREATE TABLE IF NOT EXISTS pdm_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL,
    parent_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_category_tenant ON pdm_category(tenant_id);

CREATE TABLE IF NOT EXISTS pdm_brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_brand_tenant ON pdm_brand(tenant_id);

CREATE TABLE IF NOT EXISTS pdm_spu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    sku VARCHAR(128),
    title VARCHAR(512),
    description TEXT,
    category_id VARCHAR(64),
    brand_id VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ip_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_spu_tenant ON pdm_spu(tenant_id);

CREATE TABLE IF NOT EXISTS pdm_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    spu_id VARCHAR(64) NOT NULL,
    seller_sku VARCHAR(128) NOT NULL,
    title VARCHAR(512),
    weight_kg DECIMAL(10, 4),
    declared_value DECIMAL(18, 2),
    currency VARCHAR(8),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_sku_tenant ON pdm_sku(tenant_id);
CREATE INDEX idx_pdm_sku_seller ON pdm_sku(tenant_id, seller_sku);
CREATE INDEX idx_pdm_sku_spu ON pdm_sku(spu_id);

CREATE TABLE IF NOT EXISTS pdm_selection_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    title VARCHAR(512),
    category_id VARCHAR(64),
    source VARCHAR(64),
    source_reference VARCHAR(256),
    market_analysis TEXT,
    profit_estimation TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    submitted_by VARCHAR(64),
    reviewed_by VARCHAR(64),
    review_comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_proposal_tenant ON pdm_selection_proposal(tenant_id);

CREATE TABLE IF NOT EXISTS pdm_product_development (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dev_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    spu_id VARCHAR(64) NOT NULL,
    stage VARCHAR(32) NOT NULL DEFAULT 'CONCEPT',
    stage_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdm_dev_tenant ON pdm_product_development(tenant_id);
