<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.aidotnet.erp</groupId>
        <artifactId>cross-border-erp</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>erp-app</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-dashboard</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-iam</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-pdm</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-som</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-ads</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-oms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-scm</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-wms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-fba</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-tms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-crm</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-fms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-bi</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aidotnet.erp</groupId>
            <artifactId>erp-domain-sys</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-binder</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
