ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS listing_id VARCHAR(64);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS store_id VARCHAR(64);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS marketplace VARCHAR(64);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS customer_id VARCHAR(64);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS shipping_amount DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS payment_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(32) NOT NULL DEFAULT 'UNFULFILLED';
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS risk_level VARCHAR(32);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS profit_margin DECIMAL(18, 4);
ALTER TABLE oms_sales_order ADD COLUMN IF NOT EXISTS order_date TIMESTAMP;

ALTER TABLE oms_order_line ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64);
UPDATE oms_order_line SET tenant_id = o.tenant_id FROM oms_sales_order o WHERE oms_order_line.order_id = o.order_id AND oms_order_line.tenant_id IS NULL;
ALTER TABLE oms_order_line ADD COLUMN IF NOT EXISTS product_id VARCHAR(64);
ALTER TABLE oms_order_line ADD COLUMN IF NOT EXISTS total_price DECIMAL(18, 4);
ALTER TABLE oms_order_line ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(18, 4);

CREATE TABLE IF NOT EXISTS oms_promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_id VARCHAR(64) NOT NULL UNIQUE,
    tenant_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    promo_type VARCHAR(64) NOT NULL,
    promo_code VARCHAR(128),
    discount DECIMAL(18, 4) NOT NULL DEFAULT 0,
    description VARCHAR(512),
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE oms_fulfillment_package ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64);
ALTER TABLE oms_fulfillment_package_line ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64);
UPDATE oms_fulfillment_package fp
SET tenant_id = p.tenant_id
FROM oms_fulfillment_plan p
WHERE fp.plan_id = p.plan_id
  AND fp.tenant_id IS NULL;
UPDATE oms_fulfillment_package_line fpl
SET tenant_id = p.tenant_id
FROM oms_fulfillment_package fp
JOIN oms_fulfillment_plan p ON fp.plan_id = p.plan_id
WHERE fpl.package_id = fp.package_id
  AND fpl.tenant_id IS NULL;

ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS contact_name VARCHAR(128);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS country_code VARCHAR(16);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS credit_rating VARCHAR(32);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS lead_time_days INTEGER;
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS moq INTEGER;
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE scm_supplier ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS po_number VARCHAR(128);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS payment_terms TEXT;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS shipping_terms TEXT;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS purchase_type VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS expected_delivery_date TIMESTAMP;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS actual_delivery_date TIMESTAMP;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS created_by VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS approved_by VARCHAR(64);
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE scm_purchase_order ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64);
ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS product_id VARCHAR(64);
ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS total_price DECIMAL(18, 4);
ALTER TABLE scm_purchase_order_line ADD COLUMN IF NOT EXISTS expected_date TIMESTAMP;
UPDATE scm_purchase_order_line pol
SET tenant_id = po.tenant_id
FROM scm_purchase_order po
WHERE pol.po_id = po.po_id
  AND pol.tenant_id IS NULL;
